# Generated by Django 2.0.4 on 2018-04-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(max_length=5)),
                ('comment', models.CharField(max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('productID', models.IntegerField(max_length=6)),
            ],
        ),
    ]
