# Generated by Django 2.0.4 on 2018-04-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductReview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='productID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
