# Generated by Django 2.0.4 on 2018-04-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductReview', '0002_auto_20180427_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='reviewer',
            field=models.CharField(default='', max_length=256),
        ),
    ]
